name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Prodigy.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
      
    - name: Test
      run: dotnet test --no-restore --no-build --verbosity normal
      
    - name: Create nuget packages
      run: dotnet pack
      
    - name: Publish Github
      run: dotnet nuget push "**/*.nupkg" --source https://nuget.pkg.github.com/DanielMrowca/index.json --api-key ${{secrets.NUGET_GITHUB_PAT}}  --skip-duplicate
      
    - name: Publish Nuget
      run: dotnet nuget push "**/*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_ORG_PAT}} --skip-duplicate
      
      
