name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
  
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'HoneyComb.sln'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        source-url: https://nuget.pkg.github.com/usernamecompanyname/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore
      
    - name: Test
      run: dotnet test --no-restore --no-build --verbosity normal
      
    - name: Create nuget packages
      run: dotnet pack
      
    - name: Publish nuget packages
      run: dotnet nuget push *.nupkg
      
      
